spring.application.name=Job_Portal_backend
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){green} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger{15}){yellow} - %clr(%msg%n){cyan}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:jobportaldb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
